# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI for cypress tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: 'npm'
          
      - name: Install cypress
        run: |
         npm install
      
      - name: Run tests
        run: |
         npx cypress run
         continue-on-error: true
      
      - name: Generate report
        run: |
         npm run generate-report-per-browser
